export const LSC_VOCABULARY = {
  Abecedario: [
    { label: "A", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/A.mp4" },
    { label: "B", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/B.mp4" },
    { label: "C", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/C.mp4" },
    { label: "D", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/D.mp4" },
    { label: "E", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/E.mp4" },
    { label: "F", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/F.mp4" },
    { label: "G", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/G.mp4" },
    { label: "H", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/H.mp4" },
    { label: "I", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/I.mp4" },
    { label: "J", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/J.mp4" },
    { label: "K", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/K.mp4" },
    { label: "L", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/L.mp4" },
    { label: "LL", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/LL.mp4" },
    { label: "M", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/M.mp4" },
    { label: "N", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/N.mp4" },
    { label: "Ñ", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/%C3%91.mp4" },
    { label: "O", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/O.mp4" },
    { label: "P", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/P.mp4" },
    { label: "Q", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/Q.mp4" },
    { label: "R", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/R.mp4" },
    { label: "RR", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/RR.mp4" },
    { label: "S", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/S.mp4" },
    { label: "T", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/T.mp4" },
    { label: "U", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/U.mp4" },
    { label: "V", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/V.mp4" },
    { label: "W", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/W.mp4" },
    { label: "X", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/X.mp4" },
    { label: "Y", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/Y.mp4" },
    { label: "Z", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/Z.mp4" },
  ],
  Colores: [
    { label: "AMARILLO", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/AMARILLO.mp4" },
    { label: "AMARILLO NARANJA", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/AMARILLO_NARANJA.mp4" },
    { label: "AMARILLO VERDE", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/AMARILLO_VERDE.mp4" },
    { label: "AZUL", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/AZUL.mp4" },
    { label: "AZUL VERDE", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/AZUL_VERDE.mp4" },
    { label: "AZUL VIOLETA", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/AZUL_VIOLETA.mp4" },
    { label: "BLANCO", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/AZUL_VIOLETA.mp4" },
    { label: "CAFÉ", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/CAF%C3%89.mp4" },
    { label: "COLORES", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/COLORES.mp4" },
    { label: "CREMA", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/CREMA.mp4" },
    { label: "GRIS", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/GRIS.mp4" },
    { label: "MEZCLAR", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/MEZCLAR.mp4" },
    { label: "MORADO", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/MORADO.mp4" },
    { label: "NARANJA", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/NARANJA.mp4" },
    { label: "NEGRO", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/NEGRO.mp4" },
    { label: "ROJO", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/ROJO.mp4" },
    { label: "ROJO NARANJA", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/ROJO_NARANJA.mp4" },
    { label: "ROJO VIOLETA", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/ROJO_VIOLETA.mp4" },
    { label: "VERDE", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/VERDE.mp4" },
    { label: "VIOLETA", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/VIOLETA.mp4" },
  ],
  Diseño: [
    { label: "AGUA", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/AGUA.mp4" },
    { label: "CAPAS", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/CAPAS.mp4" },
    { label: "HOJAS", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/HOJAS.mp4" },
    { label: "LÁPIZ", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/L%C3%81PIZ.mp4" },
    { label: "MATERIALES", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/MATERIALES.mp4" },
    { label: "PERSPECTIVA", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/PERSPECTIVA.mp4" },
    { label: "PINCEL", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/PINCEL.mp4" },
    { label: "SEPARAR", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/SEPARAR.mp4" },
    { label: "TEXTURA", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/SEPARAR.mp4" },
    { label: "VOLUMEN", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/VOLUMEN.mp4" },
  ],
  Oficina: [
    { label: "ENVIAR TAREA", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/ENVIAR_TAREA.mp4" },
    { label: "HORARIO", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/HORARIO.mp4" },
    { label: "HORARIO DE CLASE", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/HORARIO%20DE%20CLASE.mp4" },
    { label: "HORARIO DE MATERIA", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/HORARIO%20DE%20MATERIA.mp4" },
    { label: "MATRÍCULA ACADÉMICA", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/MATRICULA_ACADEMICA.mp4" },
    { label: "MATRICULA FINANCIERA", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/MATRICULA_FINANCIERA.mp4" },
    { label: "MATRÍCULA MATERIAS", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/MATR%C3%8DCULA_MATERIAS.mp4" },
    { label: "PROCESO DE MATRÍCULA", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/PROCESO%20DE%20MATR%C3%8DCULA.mp4" },
    { label: "SOLICITAR CERTIFICADO", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/SOLICITAR_CERTIFICADO.mp4" },
  ],
  Saludos: [
    { label: "GRACIAS", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/GRACIAS.mp4" },
    { label: "HOLA", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/HOLA.mp4" },
    { label: "MI NOMBRE", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/MI_NOMBRE.mp4" },
    { label: "MI SEÑA", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/MI_SE%C3%91A.mp4" },
    { label: "PROFESOR", url: "https://huggingface.co/manosabiertas/Manos-Abiertas-LSC/resolve/main/PROFESOR.mp4" },
  ]
};
